Inland_Wind_Farm_Dataset = {
    "TCN-effKAN": {
        'model': 'TCN-effKAN',
        'learning_rate': '0.001',
        'date_column': 'Sequence',
        'is_training': '1',
        'root_path': '/kaggle/input/zenodo5516552-wt1',
        'data_path': 'Inland Wind Farm Dataset1(WT1).csv',
        'model_id': 'TCN-effKAN_96_1',
        'seq_len': '96',
        'label_len': '48',
        'pred_len': '1',
        'e_layers': '2',
        'd_layers': '1',
        'factor': '3',
        'd_model': '16',
        'task_name': 'conv',
        'data': 'conv_ETTh1',
        'features': 'MS',
        'target': 'y',
        'enc_in': '6',
        'c_out': '1',
        'result_rpath': '/kaggle/working',
        'num_workers': '10'
    },
    "Transformer":
        {'task_name': 'short_term_forecast', 'is_training': '1', 'root_path': '/kaggle/input/zenodo5516552-wt1',
         'seasonal_patterns': "Monthly", 'model_id': '[Inland-Wind-Farm-Dataset1(WT1)]_Transformer_conv_96_1',
         'model': 'Transformer', 'data': 'former', 'features': 'MS', 'e_layers': '2', 'd_layers': '1', 'factor': '3',
         'enc_in': '6', 'dec_in': '6', 'c_out': '1', 'batch_size': '16', 'd_model': '16', 'des': 'Exp',
         'learning_rate': '0.001', 'date_column': 'Sequence',
         'data_path': 'Inland Wind Farm Dataset1(WT1).csv', 'seq_len': '96', 'label_len': '48', 'pred_len': '1',
         'target': 'y', 'result_rpath': '/kaggle/working', 'num_workers': '10',
         "loss": 'SMAPE'},
}
